### ISSUE TITLE
Add User to Interaction

### ISSUE THREAD

**Issue by North-West-Wind** [Mystiing/slashcord#1]
The `Interaction` object only has a `GuildMember` but not `User`.
When running slash commands in DMs, `interaction.member` doesn't exist and I need to get the `User` object by `client.users.fetch(channelID)`

Can you add a `user`/`author` property to `Interaction`?

**Comment by Fovex** [comment]
very likely something change since opening this issue but now  it has user object which look like this
    

```js
user: User {
      id: '',
      bot: false,
      system: false,
      flags: [UserFlags],
      username: '',
      discriminator: '',
      avatar: '',
      banner: null,
      accentColor: null
    }
  },
```
